.TH "kernel/cpu/i386/cpu_init.c" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/cpu_init.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gdt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcpu_init\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cpu_init ()"
Initialize any architecture-specific CPU things\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
