.TH "kernel/cpu/i386/gdt.h" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/gdt.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgdt_init\fP ()"
.br
.ti -1c
.RI "void \fBallow_all_ports\fP ()"
.br
.ti -1c
.RI "void \fBblock_all_ports\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void allow_all_ports ()"
Allows all ports in the IOPB\&. 
.SS "void block_all_ports ()"
Blocks all ports in the IOPB\&. 
.SS "void gdt_init ()"
Initializes the GDT & TSS\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
