.TH "gdt_description" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdt_description
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "Size of the GDT\&. "
.ti -1c
.RI "\fBgdt_entry\fP * \fBaddress\fP"
.br
.RI "Address of the GDT\&. "
.in -1c
.SH "Detailed Description"
.PP 
Pointed to by the GDTR to tell the processor the GDT's size and address\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
