.TH "kernel/cpu/halt.h" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/halt.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhalt\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void halt ()"
Clear interrupts and halt the CPU, 
.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
