.TH "kernel/cpu/i386/idt.c" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/idt.c
.SH SYNOPSIS
.br
.PP
\fC#include 'idt\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBidt_gate_t\fP"
.br
.ti -1c
.RI "struct \fBidt_register_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKERNEL_CS\fP   0x08"
.br
.RI "Kernel code segemnt selector\&. "
.ti -1c
.RI "#define \fBIDT_ENTRIES\fP   256"
.br
.RI "Number of entries in the IDT\&. "
.ti -1c
.RI "#define \fBLOW_16\fP(address)   (uint16_t)((address) & 0xFFFF)"
.br
.RI "Macro to get the low 16 bits of an address\&. "
.ti -1c
.RI "#define \fBHIGH_16\fP(address)   (uint16_t)(((address) >> 16) & 0xFFFF)"
.br
.RI "Macro to get the high 16 bits of an address\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBidt_set_gate\fP (int n, uint32_t handler)"
.br
.ti -1c
.RI "void \fBload_idt\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBidt_gate_t\fP \fBidt\fP [\fBIDT_ENTRIES\fP]"
.br
.RI "The IDT\&. "
.ti -1c
.RI "static \fBidt_register_t\fP \fBidt_reg\fP"
.br
.RI "The value to load into the IDTR\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void idt_set_gate (int n, uint32_t handler)"
Sets an IDT gate\&. 
.PP
\fBParameters\fP
.RS 4
\fIn\fP the IDT gate to set 
.br
\fIhandler\fP the handler for the gate\&. 
.RE
.PP

.SS "void load_idt ()"
Loads the IDT 
.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
