.TH "idt_register_t" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idt_register_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBlimit\fP"
.br
.RI "Size of the IDT\&. "
.ti -1c
.RI "\fBidt_gate_t\fP * \fBbase\fP"
.br
.RI "Address of the IDT\&. "
.in -1c
.SH "Detailed Description"
.PP 
Pointed to by the IDTR to tell the processor the IDT's size and address\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
