.TH "kernel/cpu/i386/isr.c" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/isr.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./kernel\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./tasking\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./vga_err\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./address_spaces\&.h'\fP
.br
\fC#include '\&.\&./halt\&.h'\fP
.br
\fC#include '\&.\&./isr\&.h'\fP
.br
\fC#include '\&.\&./paging\&.h'\fP
.br
\fC#include '\&.\&./serial\&.h'\fP
.br
\fC#include 'gdt\&.h'\fP
.br
\fC#include 'idt\&.h'\fP
.br
\fC#include 'isr\&.h'\fP
.br
\fC#include 'interrupt\&.h'\fP
.br
\fC#include <cpu/ports\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/syscalls\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBirq_handler\fP (\fBregisters_t\fP *r)"
.br
.ti -1c
.RI "void \fBisr_install\fP ()"
.br
.ti -1c
.RI "void \fBisr_handler\fP (\fBregisters_t\fP *r)"
.br
.ti -1c
.RI "void \fBisr_register_handler\fP (int n, \fBisr_t\fP handler)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBisr_t\fP \fBirq_handlers\fP [16]"
.br
.RI "Handlers for the PIC interrupts\&. "
.ti -1c
.RI "static char * \fBexception_messages\fP []"
.br
.RI "List of messages for each exception\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void irq_handler (\fBregisters_t\fP * r)"
Handler for PIC interrupts 
.PP
\fBParameters\fP
.RS 4
\fIr\fP The saved state of the CPU 
.RE
.PP

.SS "void isr_handler (\fBregisters_t\fP * r)"
Handler for non-PIC interrupts 
.PP
\fBParameters\fP
.RS 4
\fIr\fP The saved state of the CPU 
.RE
.PP

.SS "void isr_install ()"
Install the interrupt handlers into the IDT\&. 
.SS "void isr_register_handler (int n, \fBisr_t\fP handler)"
Register an IRQ handler 
.PP
\fBParameters\fP
.RS 4
\fIn\fP the IRQ to register a handler for 
.br
\fIhandler\fP the handler to register 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
