.TH "registers_t" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
registers_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBds\fP"
.br
.RI "Data segment selector\&. "
.ti -1c
.RI "uint32_t \fBedi\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBesi\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBebp\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBesp\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBebx\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBedx\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBecx\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBeax\fP"
.br
.RI "Pushed by pusha\&. "
.ti -1c
.RI "uint32_t \fBint_no\fP"
.br
.RI "Interrupt number\&. "
.ti -1c
.RI "uint32_t \fBerr_code\fP"
.br
.RI "Error code (if applicable) "
.ti -1c
.RI "uint32_t \fBeip\fP"
.br
.RI "Pushed by the processor automatically\&. "
.ti -1c
.RI "uint32_t \fBcs\fP"
.br
.RI "Pushed by the processor automatically\&. "
.ti -1c
.RI "uint32_t \fBeflags\fP"
.br
.RI "Pushed by the processor automatically\&. "
.ti -1c
.RI "uint32_t \fBuseresp\fP"
.br
.RI "Pushed by the processor automatically\&. "
.ti -1c
.RI "uint32_t \fBss\fP"
.br
.RI "Pushed by the processor automatically\&. "
.in -1c
.SH "Detailed Description"
.PP 
Saved state of the CPU when an interrupt occurs 

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
