.TH "RPCFuncInfo" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCFuncInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rpc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [32]"
.br
.RI "THe name of the function\&. "
.ti -1c
.RI "void *(* \fBcode\fP )(void *)"
.br
.RI "A pointer to the code that implements the funtcion\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an RPC fumctiom 

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
