.TH "kernel/cpu/serial.h" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/serial.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBserial_init\fP ()"
.br
.ti -1c
.RI "void \fBserial_putc\fP (char c)"
.br
.ti -1c
.RI "void \fBserial_write_string\fP (const char *s)"
.br
.ti -1c
.RI "void \fBserial_printf\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void serial_init ()"
Initialize the serial driver 
.SS "void serial_printf (const char * format,  \&.\&.\&.)"
Printf, but to the serial port 
.PP
\fBParameters\fP
.RS 4
\fIformat\fP The format string 
.br
\fI\&.\&.\&.\fP Arguments for the format string 
.RE
.PP
\fBNote\fP
.RS 4
This function is provided by platform-independent code, a serial driver does not need to implement this\&. 
.RE
.PP

.SS "void serial_putc (char c)"
Write a character to the serial port 
.PP
\fBParameters\fP
.RS 4
\fIc\fP The character to write 
.RE
.PP

.SS "void serial_write_string (const char * s)"
Write a string to the serial port 
.PP
\fBParameters\fP
.RS 4
\fIs\fP The string to write 
.RE
.PP
\fBNote\fP
.RS 4
This function is provided by platform-independent code, a serial driver does not need to implement this\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
