.TH "kernel/cpu/i386/serial.c" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/serial.c
.SH SYNOPSIS
.br
.PP
\fC#include <cpu/ports\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATA_PORT\fP(com)   (\fBdata_ports\fP[com])"
.br
.RI "Returns the data port of a serial port\&. "
.ti -1c
.RI "#define \fBINT_PORT\fP(com)   (\fBDATA_PORT\fP(com)+1)"
.br
.RI "Returns the interrupt config port of a serial port\&. "
.ti -1c
.RI "#define \fBFIFO_PORT\fP(com)   (\fBDATA_PORT\fP(com)+2)"
.br
.RI "Returns the fifo config port of a serial port\&. "
.ti -1c
.RI "#define \fBLINE_CMD_PORT\fP(com)   (\fBDATA_PORT\fP(com)+3)"
.br
.RI "Returns the line cmd port of a serial port\&. "
.ti -1c
.RI "#define \fBMODEM_CMD_PORT\fP(com)   (\fBDATA_PORT\fP(com)+4)"
.br
.RI "Returns the modem cmd port of a serial port\&. "
.ti -1c
.RI "#define \fBLINE_STAT_PORT\fP(com)   (\fBDATA_PORT\fP(com)+5)"
.br
.RI "Returns the line status port of a serial port\&. "
.ti -1c
.RI "#define \fBSCRATCH_PORT\fP(com)   (\fBDATA_PORT\fP(com)+7)"
.br
.RI "Returns the scratch port of a serial port\&. "
.ti -1c
.RI "#define \fBIS_TRANSMIT_FIFO_EMPTY\fP(com)   (port_byte_in(\fBLINE_STAT_PORT\fP(com))&0x20)"
.br
.RI "Returns whether the trasmit FIFO is empty\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBconfigure\fP (int com, int rate)"
.br
.ti -1c
.RI "void \fBserial_init\fP ()"
.br
.ti -1c
.RI "void \fBserial_putc\fP (char c)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char \fBconfigured\fP [] ={0,0,0,0}"
.br
.RI "What serial ports have been detected and configured\&. "
.ti -1c
.RI "static int \fBdata_ports\fP [4] ={0x3f8,0x2f8,0x3e8,0x2e8}"
.br
.RI "List of the data ports for all the potential serial ports\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void configure (int com, int rate)\fC [static]\fP"
Configure a serial port with a specified baud rate\&. 
.PP
\fBParameters\fP
.RS 4
\fIcom\fP The number of the serial port to configure 
.br
\fIrate\fP The baud rate to set the serial port to\&. 
.RE
.PP

.SS "void serial_init ()"
Initialize the serial driver 
.SS "void serial_putc (char c)"
Write a character to the serial port 
.PP
\fBParameters\fP
.RS 4
\fIc\fP The character to write 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
