.TH "kernel/cpu/i386/tasking_helpers_c.c" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/cpu/i386/tasking_helpers_c.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./tasking\&.h'\fP
.br
\fC#include '\&.\&./paging\&.h'\fP
.br
\fC#include '\&.\&./tasking_helpers\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./pmem\&.h'\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char \fBis_kstack_allocated\fP (size_t index)"
.br
.ti -1c
.RI "static void \fBmark_kstack_allocated\fP (size_t index)"
.br
.ti -1c
.RI "static int \fBnew_kstack\fP ()"
.br
.ti -1c
.RI "void \fBsetup_kstack\fP (\fBThread\fP *thread, void *param1, void *param2, char kmode, void *eip)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static void ** \fBkstacks\fP =(void*)0xC8000000"
.br
.RI "Pointer to all the thread kernel stacks\&. "
.ti -1c
.RI "static char \fBkstack_bmap\fP [(218 *1024)/8] ={0}"
.br
.RI "Bitmap of what kernel stacks have been allocated\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "static char is_kstack_allocated (size_t index)\fC [static]\fP"
Check whether a kernel stack is allocated 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The kernel stack to check 
.RE
.PP
\fBReturns\fP
.RS 4
whether the kernel stack is allocated 
.RE
.PP

.SS "static void mark_kstack_allocated (size_t index)\fC [static]\fP"
Mark that a kernel stack is allocated 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The kernel stack to mark 
.RE
.PP

.SS "static int new_kstack ()\fC [static]\fP"
Allocate a kernel stack for a thread 
.PP
\fBReturns\fP
.RS 4
The number of the new kernel stack, or -1 if none are unallocated\&. 
.RE
.PP

.SS "void setup_kstack (\fBThread\fP * thread, void * param1, void * param2, char kmode, void * eip)"
Setup a kernel stack for a thread 
.PP
\fBParameters\fP
.RS 4
\fIthread\fP The thread to setup a stack for 
.br
\fIparam1\fP The thread's start function first parameter 
.br
\fIparam2\fP The thread's start function second parameter 
.br
\fIkmode\fP Whether the thread is a kernel mode thread 
.br
\fIeip\fP The start address of the thread 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
