.TH "kernel/vga_err.h" 9 "Sun Jul 26 2020" "MyOS Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel/vga_err.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvga_init\fP (char *\fBscreen\fP)"
.br
.ti -1c
.RI "void \fBvga_write_string\fP (const char *string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void vga_init (char * screen)"
Initilaze the VGA error writing driver 
.PP
\fBParameters\fP
.RS 4
\fIscreen\fP Pointer to VGA screen memory 
.RE
.PP

.SS "void vga_write_string (const char * string)"
Write a string starting at the top line of the VGA display 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to write 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MyOS Kernel from the source code\&.
