#ifndef SYSCALLS_H

#define SYSCALLS_H

#define SYSCALL_CREATEPROC 0
#define SYSCALL_YIELD 1
#define SYSCALL_BLOCK 2
#define SYSCALL_UNBLOCK 3
#define SYSCALL_EXIT 4
#define SYSCALL_GET_ERRNO_ADDR 5
#define SYSCALL_GET_PID 6
#define SYSCALL_NEW_THREAD 14

#define SYSCALL_ALLOC_MEM 7
#define SYSCALL_PRIV_MAP_PAGES 8
#define SYSCALL_NEW_ADDR_SPACE 9
#define SYSCALL_ADDR_SPACES_COPY_DATA 10

#define SYSCALL_SERIAL_PRINT 11
#define SYSCALL_GET_INITRD_SZ 12
#define SYSCALL_COPY_INITRD 13

#endif
