#ifndef SYSCALLS_H

#define SYSCALLS_H

#define SYSCALL_CREATEPROC_NEW_ADDR_SPACE 1
#define SYSCALL_CREATEPROC_GIVEN_ADDR_SPACE 2
#define SYSCALL_CREATEPROC_GIVEN_ADDR_SPACE_W_ARGS 3
#define SYSCALL_YIELD 4
#define SYSCALL_YIELD_TO_PID 5
#define SYSCALL_BLOCK 6
#define SYSCALL_UNBLOCK 7
#define SYSCALL_EXIT 8
#define SYSCALL_GET_ERRNO_ADDR 9
#define SYSCALL_GET_PID 10
#define SYSCALL_ALLOC_MEM 11
#define SYSCALL_ALLOC_MEM_VIRT 12
#define SYSCALL_PRIV_MAP_PAGES 13
#define SYSCALL_NEW_ADDR_SPACE 14
#define SYSCALL_ADDR_SPACES_COPY_DATA 15
#define SYSCALL_ADDR_SPACES_PUT_DATA 16
#define SYSCALL_SERIAL_PRINT 17
#define SYSCALL_GET_INITRD_SZ 18
#define SYSCALL_COPY_INITRD 19

#endif
