#ifndef SYSCALLS_H

#define SYSCALLS_H

#define SYSCALL_YIELD 1
#define SYSCALL_CREATEPROC_NEW_ADDR_SPACE 2
#define SYSCALL_ALLOC_MEM 3
#define SYSCALL_ALLOC_MEM_VIRT 4
#define SYSCALL_GET_ERRNO_ADDR 5
#define SYSCALL_NEW_ADDR_SPACE 8
#define SYSCALL_CREATEPROC_GIVEN_ADDR_SPACE 9
#define SYSCALL_ADDR_SPACES_COPY_DATA 10
#define SYSCALL_PRIV_MAP_PAGES 11
#define SYSCALL_CREATEPROC_GIVEN_ADDR_SPACE_W_ARGS 12
#define SYSCALL_ADDR_SPACES_PUT_DATA 13
#define SYSCALL_YIELD_TO_PID 15
#define SYSCALL_SERIAL_PRINT 16
#define SYSCALL_EXIT 17
#define SYSCALL_GET_INITRD_SZ 18
#define SYSCALL_COPY_INITRD 19
#define SYSCALL_GET_PID 20
#define SYSCALL_BLOCK 22
#define SYSCALL_UNBLOCK 23
#endif
